config/routes.rb
Rails.application.routes.draw do
  resources :posts

  get 'carts/add'

  get 'users/new'

  get 'about/index'

  resources :line_items, only: [:delete]
  
  resources :sections
  resources :users
    
  resources :carts, only: [:show]
  resources :food_items

  get "contact_us" => "home#contact_us"
  get "cart" => "carts#show"
  post  "carts/add"

  #get "menu"=> "sections#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  def item_count 
    line_items.count
  end
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
  validates :name, :price, presence: true
  belongs_to :section
  has_many :line_items, dependent: :destroy

  def fake_image_url
    
    "http://www.veganfoodquest.com/wp-content/uploads/2014/09/IMG_2672-1024x783.jpg" 
  end 

end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :food_item
  belongs_to :cart
  validates :quantity,
    presence: true,
    numericality: {
      greate_than: 0, less_than:  10, only_integer: true 

    }
    def name 
      food_item.name
    end
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/section.rb
class Section < ApplicationRecord
  has_many :food_items
  
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def add
     
    cart = get_cart
    line_item = cart.line_items.build line_item_params
    if cart.save
      flash[:success] = "You added"
    else
      flash[:error] = "Cannot add #{line_item.food_item.name}. Error: #{line_item.errors.full_messages.to_sentence}"
    end 
    redirect_back(fallback_location: sections_path)
  end 
 
  def show
     
  end

  private
  def line_item_params
    params.require(:line_item).permit(:food_item_id, :quantity)
  end 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
  
      

  def contact_us
  end  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController

  def index
    unless params[:section]
      redirect_to sections_path(section: Section.first.name)
      return 
    end 

    @sections = Section.all
    section = Section.find_by(name: params[:section])
    @food_items = section.food_items
    get_cart
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:index]
  
  def new
    @user = User.new
  end

  def create
    redirect_to root_path
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flasherize(key)
    case key.to_sym
  when :error
    "alert-danger"
  when :success
    "alert-success"
  else
    "alert-warning"
  end
end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/section_helper.rb
module SectionHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/sections/index.html.erb
<div class="tabs is-centered is-boxed is-large">
  <ul>
    <% @sections.each do |section| %>
      <li class="<%= 'is-active' if params[:section] == section.name %>"> 
        <%= link_to(section.name, sections_path(section: section.name)) %>
      </li>  
    <% end %>
  </ul>
</div>
    <% if @food_items.present? %>
    <br></br>
    <% @food_items.in_groups_of(3) do |group| %>
      <div class="columns">
        <% group.compact.each do |food_item| %>
          <div class="column is-4">
            <div class="card">
              <div class="card-image">
                <figure class="image is-4by3">
                  <img src="<%= food_item.fake_image_url %>" alt="Image">
                </figure>
              </div>
              <div class="card-content">
                <div class="media">
                  <div class="media-content">
                    <p class="title is-4"><%= food_item.name %>:<br> <%= number_to_currency(food_item.price) %></p>
                    <p class="subtitle is-6"><%= food_item.description %></p>

                    <%= form_for LineItem.new(food_item: food_item), url: carts_add_path do |f| %>
                      <%= f.hidden_field :food_item_id %>
                      <%= f.number_field :quantity, class: "input" %>
                      <%= f.submit "Order", class: "button is-primary"  %>
                    <% end %>

                    <%= form_tag food_item_path(food_item.id), method: :delete do %>
                      <%= submit_tag "Delete", class: " hidden button is-primary", style:"margin: 10px" %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
       <% end %>
      </div>
    <% end %>
 </div>
 </div>