config/routes.rb
Rails.application.routes.draw do
  resources :posts

  get 'carts/add'

  get 'users/new'

  get 'about/index'

  resources :line_items, only: [:delete]
  
  resources :sections
  resources :users
    
  resources :carts, only: [:show]
  resources :food_items

  get "contact_us" => "home#contact_us"
  get "cart" => "carts#show"
  post  "carts/add"

  #get "menu"=> "sections#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  def item_count 
    line_items.count
  end
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
  validates :name, :price, presence: true
  belongs_to :section
  has_many :line_items, dependent: :destroy

  def fake_image_url
    
    "http://www.veganfoodquest.com/wp-content/uploads/2014/09/IMG_2672-1024x783.jpg" 
  end 

end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :food_item
  belongs_to :cart
  validates :quantity,
    presence: true,
    numericality: {
      greate_than: 0, less_than:  10, only_integer: true 

    }
    def name 
      food_item.name
    end
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/section.rb
class Section < ApplicationRecord
  has_many :food_items
  
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def add
     
    cart = get_cart
    line_item = cart.line_items.build line_item_params
    if cart.save
      flash[:success] = "You added"
    else
      flash[:error] = "Cannot add #{line_item.food_item.name}. Error: #{line_item.errors.full_messages.to_sentence}"
    end 
    redirect_back(fallback_location: sections_path)
  end 
 
  def show
     
  end

  private
  def line_item_params
    params.require(:line_item).permit(:food_item_id, :quantity)
  end 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
  
      

  def contact_us
  end  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flasherize(key)
    case key.to_sym
  when :error
    "alert-danger"
  when :success
    "alert-success"
  else
    "alert-warning"
  end
end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/section_helper.rb
module SectionHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/about/index.html.erb
<div class="content">
<h1> <%= link_to "Đăng Ký Hội Viên Câu Lạc Bộ Chay" , users_new_path %> </h1>
<p>Nơi trau dồi kiến thức, kết bạn và thiện nguyện cho tất cả các bạn yêu thích nghệ thuật Thuần Chay</p>

<p class="title is-4" style= "color:hsl(171, 100%, 41%)"><strong>Lợi ích của việc ăn chay</strong></p>

<h1>Lợi ích</h1>
<p>Ăn chay hiện là một xu hướng của nhiều người hiện nay muốn bảo vệ sức khỏe.Người ta ăn chay vì nhiều lý do khác nhau, có người ăn chay vì sở thích, có người ăn chay vì sức khỏe, có người ăn chay vì đạo, hoặc ăn vì những mục tiêu của cuộc sống như bảo vệ môi trường, bảo vệ động vật, nên ăn chay cũng chia ra nhiều trường phái khác nhau, ăn chay toàn phần là cách ăn bỏ hẳn tất cả những thứ có nguồn góc động vật ra khỏi khẩu phần ăn hằng ngày, hay ăn chay bán phần, không ăn thịt cá, hải sản, nhưng sữa trứng thì vẫn ăn.</p>

<p>Dù mục tiêu và cách ăn chay của bạn như thế nào, thì việc ăn chay cũng là một điều vô cùng đáng khích lệ. Ăn chay có muôn vàn lợi ích, cái lợi ích hàng đầu của việc ăn chay chính tốt cho sức khỏe con người.</p>
  

<h2>Những danh nhân nổi tiếng ăn chay trên thế giới như: </h2>
<p><strong> - Léonard Da Vinci </strong>: ông ăn chay vì nhà danh họa và điêu khắc gia người Ý, đồng thời cũng là một thi sĩ nổi tiếng trên thế giới quan niệm ăn chay là đạo đức của con người. Sự ăn chay sẽ tránh được những tội ác về sát sinh. Ông còn nhấn mạnh rằng những ai không biết quý trọng sự sống của những sinh vật khác là những kẻ không đáng sống.</p>
  <figure>
    <img src="http://www.leonardodavinci.net/images/leonardo-da-vinci.jpg">
    <figcaption>
      Leonardo Da Vinci
    </figcaption>
  </figure>
<p><strong> -Albert Einstein: </strong> Ông là một người yêu chuộng hòa bình, tôn trọng sự sống của muôn loài và đã từng phát biểu: “Không gì ích lợi cho sức khỏe của con người để có cơ hội sống lâu trên quả địa cầu này bằng cách ăn chay”.</p>
  <figure>
    <img src="https://i.pinimg.com/originals/08/95/70/08957029ae31bceb6eae1f03d88b6d22.jpg">
    <figcaption>
      Albert Einstein
    </figcaption>
  </figure>
<p> <strong> – Steve Jobs </strong> : ông trùm kinh doanh và sáng chế người Mỹ, một trong những người sáng lập Apple cũng là một người ăn chay và ủng hộ lối sống khỏe, thân thiện môi trường và bảo vệ động vật với PETA. Ông từng tặng rất nhiều Contairner chứa nước ép cà rốt tại buổi Haloween thay vì tặng kẹo.</p>
  <figure>
    <img src="https://i.ytimg.com/vi/IMWnwG2fjb0/hqdefault.jpg">
    <figcaption>
      Steve Jobs
    </figcaption>
  </figure>

<h2></h2>
<p>Việc ăn chay mang nhiều lợi ích thiết thực, nhưng không phải ai cũng ăn chay được. Khi chúng ta đã quen ăn mặn, việc khởi đầu ăn chay không phải dễ dàng gì. Nên ẩm thực chay Việt Nam cũng phong phú đa dạng để phục vụ cho những nhu cầu đó. Giúp người ăn cảm thấy quen dần với ăn chay bỏ dần ăn mặn dễ dàng.</p>

app/views/home/contact_us.html.erb
<p class="title is-4" style= "color:hsl(171, 100%, 41%)"><strong>Yên Restaurant</strong></p>
<div class="col-md-6">
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1949.6158499437558!2d109.19483151026806!3d12.232584999392776!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x317067648ab22c69%3A0xb6dfa9d97a610b2f!2sY%E1%BA%BFn+Restaurant+%40havanhotel!5e0!3m2!1sen!2sin!4v1504176653835" 
      width="500" height="350" frameborder="12" style="border:0" allowfullscreen></iframe>   
  </div>
  
<div class="media-content">
  <div class="content" style= "color:hsl(141, 71%, 48%)">
      <br>Tran Quang Khai Street <br>District 1<br>Ho Chi Minh City<br>VietNam<br>
      Yenrestaurant@gmail.com <br
    <small>Open 9:00 AM - 11:00 PM </small>
  </div> 
</div> 

app/views/home/index.html.erb
  <div class="w3-display-middle w3-large">
    <%= image_tag "https://thumbs.dreamstime.com/z/food-fresh-vegetables-page-header-website-panel-51710717.jpg"%>
</div>