config/routes.rb
Rails.application.routes.draw do
  resources :posts

  get 'carts/add'

  get 'users/new'

  get 'about/index'

  resources :line_items, only: [:delete]
  
  resources :sections
  resources :users
    
  resources :carts, only: [:show]
  resources :food_items

  get "contact_us" => "home#contact_us"
  get "cart" => "carts#show"
  post  "carts/add"

  #get "menu"=> "sections#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  def item_count 
    line_items.count
  end
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
  validates :name, :price, presence: true
  belongs_to :section
  has_many :line_items, dependent: :destroy

  def fake_image_url
    
    "http://www.veganfoodquest.com/wp-content/uploads/2014/09/IMG_2672-1024x783.jpg" 
  end 

end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :food_item
  belongs_to :cart
  validates :quantity,
    presence: true,
    numericality: {
      greate_than: 0, less_than:  10, only_integer: true 

    }
    def name 
      food_item.name
    end
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/section.rb
class Section < ApplicationRecord
  has_many :food_items
  
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
  
      

  def contact_us
  end  
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flasherize(key)
    case key.to_sym
  when :error
    "alert-danger"
  when :success
    "alert-success"
  else
    "alert-warning"
  end
end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/section_helper.rb
module SectionHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yen Restaurant</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<section class="hero is-primary">
  <div class="hero-body">
    <div class="container">
        <a class="nav-item" href="<%=root_path %>">        
        <strong> Yên Restaurant</strong>  
          <span class="icon is-large ">
            <i class="fa fa-cutlery"></i>
          </span>
        </a>
  <div class="tabs is-centered">
    <ul>
      <li><a><%= link_to "Menu", sections_path %></a></li>
      <li><a><%= link_to "Contact Us", contact_us_path %></a></li>
      <li><a><%= link_to "About VegansFood", about_index_path %></a></li>
      <li><a><%= link_to "Cart",cart_path %></a></li>
    </ul>
  </div>
</section>

    <% flash.each do |key, value| %>
      <div class="alert <%= flasherize(key) %>"><% value %></div>
     <% end %> 

  <div class="container">
    <%= yield %> 
  </div>
</body>
</html>